### 记忆搜索
POST {{host}}/api/v1/generate
Content-Type: application/json

{
  "prompt": "谁是你的主人"
}

### 向助手提问
POST {{host}}/api/v1/generate
Content-Type: application/json

{
  "prompt": "鲁迅真实姓名"
}

### 记忆训练
POST {{host}}/api/v1/train
Content-Type: application/json

{
  "input": [
    "我是你的主人，以后叫我石头"
  ]
}