### 向助手提问
POST {{host}}/api/v1/generate
Content-Type: application/json

{
  "prompt": "2025年9月24日发生了什么"
}

### 训练助手
POST {{host}}/api/v1/train
Content-Type: application/json

{
  "input": [
    "哈尔滨松花江畔挂起国旗喜迎国庆",
    "浙江仙居：小学生做无接触式眼保健操 提高科学用眼知识",
    "安徽通报8起违反中央八项规定精神问题",
    "河南济源：云海中风电场 太阳染金地面",
    "神舟二十号航天员乘组将于近日择机实施第四次出舱活动",
    "边走边谭：联动15国军官揭露日军侵华罪行",
    "“两点一存”耀华夏丨征服腊子口 一位“无名”英雄的长征故事",
    "“智造无界”引领工业新未来 抢抓新风口为工业转型升级创新提供中国方案",
    "既是田间喜讯 更是民生福祉提升 多视角看农民生活变迁 感受乡村振兴新图景",
    "“一站式”联合处置！司法“轻骑兵”把司法服务送到牧民的草场里、毡房旁",
    "2025年9月24日，在京举行党日活动",
    "2025年9月24日，广东遭遇桦加沙台风影响，实行五停"
  ]
}